package co.edu.itp.svu.domain;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.Instant;
import java.time.temporal.ChronoUnit;

public class RespuestaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRespuestaAllPropertiesEquals(Respuesta expected, Respuesta actual) {
        assertRespuestaAutoGeneratedPropertiesEquals(expected, actual);
        assertRespuestaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRespuestaAllUpdatablePropertiesEquals(Respuesta expected, Respuesta actual) {
        assertRespuestaUpdatableFieldsEquals(expected, actual);
        assertRespuestaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRespuestaAutoGeneratedPropertiesEquals(Respuesta expected, Respuesta actual) {
        assertThat(expected)
            .as("Verify Respuesta auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRespuestaUpdatableFieldsEquals(Respuesta expected, Respuesta actual) {
        assertThat(expected)
            .as("Verify Respuesta relevant properties")
            .satisfies(e -> assertThat(e.getContenido()).as("check contenido").isEqualTo(actual.getContenido()))
            .satisfies(e -> {
                Instant expectedFecha = e.getFechaRespuesta();
                Instant actualFecha = actual.getFechaRespuesta();
                Instant expectedTruncated = expectedFecha == null ? null : expectedFecha.truncatedTo(ChronoUnit.MILLIS);
                Instant actualTruncated = actualFecha == null ? null : actualFecha.truncatedTo(ChronoUnit.MILLIS);
                Instant epochTruncated = Instant.ofEpochMilli(0L).truncatedTo(ChronoUnit.MILLIS);
                if (expectedTruncated == null || expectedTruncated.equals(epochTruncated)) {
                    assertThat(actualTruncated == null || actualTruncated.equals(epochTruncated)).as("check fechaRespuesta").isTrue();
                } else {
                    assertThat(expectedTruncated).as("check fechaRespuesta").isEqualTo(actualTruncated);
                }
            });
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRespuestaUpdatableRelationshipsEquals(Respuesta expected, Respuesta actual) {
        assertThat(expected)
            .as("Verify Respuesta relationships")
            .satisfies(e -> assertThat(e.getPqrs()).as("check pqr").isEqualTo(actual.getPqrs()));
    }
}
