name: Build docker SVU image and deploy to VM

on:
  pull_request:
    types: [opened, synchronize, reopened]
  #release:
  #types: [published]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/itp-svu

jobs:
  build-and-push:
    name: Generate Docker image and push to registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker image with Jib
        run: ./mvnw package -Pprod -DskipTests jib:build -Djib.to.image=${{ env.IMAGE_NAME }}:latest

      - name: Print image details
        run: echo "Pushed image ${{ env.IMAGE_NAME }}:latest"

  deploy-to-vm:
    name: Deploy app to GCP VM via SSH
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM using SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            cd ~/svu/

            docker pull ${{ env.IMAGE_NAME }}:latest

            docker compose -f app.yml down
            docker compose -f app.yml pull
            docker compose -f app.yml up -d --remove-orphans
