name: Connect to VPN and SSH

on:
  push:
    branches:
      - 142-refactor-cd-vpn

env:
  IMAGE_NAME: ventanillaunica

jobs:
  build-and-deploy:
    name: Build, Push, and Deploy SVU
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker image with Jib
        run: ./mvnw package -Pprod -DskipTests jib:build -Djib.to.image=${{ env.IMAGE_NAME }}:latest

      - name: Prepare deployment directory and copy assets
        run: |
          mkdir -p /opt/svu
          cp app.yml /opt/svu/
          
          echo "SPRING_MAIL_USERNAME=${{ secrets.SPRING_MAIL_USERNAME }}" > /opt/svu/.env
          echo "SPRING_MAIL_PASSWORD=${{ secrets.SPRING_MAIL_PASSWORD }}" >> /opt/svu/.env
          echo "JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET=${{ secrets.JHIPSTER_JWT_SECRET }}" >> /opt/svu/.env
          echo "GOOGLE_RECAPTCHA_SECRET_KEY=${{ secrets.GOOGLE_RECAPTCHA_SECRET_KEY}}" >> /opt/svu/.env

      - name: Deploy app via Docker Compose
        working-directory: /opt/svu
        run: |
          docker compose -f app.yml down
          docker compose -f app.yml pull
          docker compose -f app.yml up -d --remove-orphans
